spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/kltn_payment_service?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 5009
internal:
  service:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aGVtIHJ1dCB0aWVuIiwibmFtZSI6ImR1YyIsImlhdCI6NDMyMDAzfQ.L1HlqgP2FBfE3DNXtJsFbkpg8TF82QUaUi7DCVb-4mM

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
